spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
        # Usei 'create' para apagar tudo e recriar novamente a cada execução
      ddl-auto: create # validate: Flyway cuida da estrutura, o Hibernate só valida
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
  # DesativeI o Flyway para evitar conflitos de checksum
    enabled: FALSE
    locations: classpath:db/migration
